### ISSUE TITLE
Verbose output for debugging?

### ISSUE THREAD

**Issue by surak** [pre-commit/mirrors-autopep8#8]
I'm trying it in some repo, and this is what I get:

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/surak/.cache/pre-commit/patch1610465808.
autopep8.................................................................Failed
- hook id: autopep8
- files were modified by this hook
[INFO] Restored changes from /Users/surak/.cache/pre-commit/patch1610465808.
```

autopep8 on the file works, so I don't know where the Failed message comes from or what it means.

**Comment by asottile** [comment]
the first line indicates you have unstaged changes that probably are what's confusing you, run `git status` and/or `git diff` and debug from there

you can also enable verbose mode for autopep8 via `args`, but you probably don't need to
